// ConsultationForm Form Types
// Generated by form_converter tool

export interface ConsultationFormFormData {
  // Other fields
  /** Free text field for documenting prior treatment history */
  treatment_history?: string;
  /** Patient's pulse rate */
  pulse?: number;
  /** Patient's pulse rate per minute */
  pulse_per_min?: number;
  /** Detailed description of examination findings */
  examination_description?: string;
  /** Right carotid pulse examination findings */
  carotid_right?: string;
  /** Right radial pulse examination findings */
  radial_right?: string;
  /** Right brachial pulse examination findings */
  brachial_right?: string;
  /** Right femoral pulse examination findings */
  femoral_right?: string;
  /** Right popliteal pulse examination findings */
  popliteal_right?: string;
  /** Right posterior tibial artery pulse examination findings */
  pta_right?: string;
  /** Right dorsalis pedis artery pulse examination findings */
  dpa_right?: string;
  /** Left carotid pulse examination findings */
  carotid_left?: string;
  /** Left radial pulse examination findings */
  radial_left?: string;
  /** Left brachial pulse examination findings */
  brachial_left?: string;
  /** Left femoral pulse examination findings */
  femoral_left?: string;
  /** Left popliteal pulse examination findings */
  popliteal_left?: string;
  /** Left posterior tibial artery pulse examination findings */
  pta_left?: string;
  /** Left dorsalis pedis artery pulse examination findings */
  dpa_left?: string;
  /** Blood pressure measurement for right upper limb in supine position */
  bp_right_upper_limb_supine?: string;
  /** Blood pressure measurement for right upper limb in sitting position */
  bp_right_upper_limb_sitting?: string;
  /** Blood pressure measurement for right upper limb in standing position */
  bp_right_upper_limb_standing?: string;
  /** Blood pressure measurement for left upper limb in supine position */
  bp_left_upper_limb_supine?: string;
  /** Blood pressure measurement for left upper limb in sitting position */
  bp_left_upper_limb_sitting?: string;
  /** Blood pressure measurement for left upper limb in standing position */
  bp_left_upper_limb_standing?: string;
  /** Blood pressure measurement for right lower limb in supine position */
  bp_right_lower_limb_supine?: string;
  /** Blood pressure measurement for right lower limb in sitting position */
  bp_right_lower_limb_sitting?: string;
  /** Blood pressure measurement for right lower limb in standing position */
  bp_right_lower_limb_standing?: string;

}

export interface CreateConsultationFormFormInput {
  form_type: 'pre_consultation' | 'during_consultation';
  status?: 'draft' | 'partial' | 'completed';
  appointment_id?: string;
  consultation_form_data: Partial<ConsultationFormFormData>;
}

export interface ConsultationFormForm {
  id: string;
  patient_id: string;
  appointment_id: string | null;
  form_type: 'pre_consultation' | 'during_consultation';
  status: 'draft' | 'partial' | 'completed';
  consultation_form_data: ConsultationFormFormData;
  created_at: string;
  updated_at: string;
}